server:
  host: localhost
  port: 8090
  context-path: /politikei
helianto:
  host: localhost
  title: Politikei
  base-name: politikei
  api:
    url: http://${helianto.host}:8081
spring:
  datasource:
    initialize: true
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
  freemarker:
    template-loader-path: classpath:/templates/, /templates/
    prefer-file-system-access: false
security:
  oauth2:
    client:
      client-id: iservport-trusted-client
      scope: read,write
      authorized-grant-types: authorization_code
      accessTokenUri: http://localhost:8081/oauth/token
      userAuthorizationUri: http://localhost:8081/oauth/authorize
    resource:
      jwt:
#        key-uri: http://localhost:8081/oauth/token_key
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApUzN1WkOas3R8908zqos
          WPqfZW0JEXqApe9/jRBQM2sCmdoRSTTeF53OQeDfBpKNYjeVk2WDVd694Mil2yuZ
          jhqvkRbV51OndCq41Zve45HHNK63mdwd7s0QpPrL0m/QAn3XkduLIW/NlVkR6oQX
          k4EHNx+8AjBPbEVyIPpr71549isjECyI9Nh2rooR+g9pEk/U52YGtW1PjYBT9NRJ
          MatpqJ7dv02Iu5sF32wopHGe/rCgFX2XdHrWRCjpX0gkeNtD0QK5JRMLerySlF0c
          kcI3PnDDFLhGGxxylT9FaYEW50HYnHaBIKQfXcBpf8yHka3wkeR+t1Wrpu3vcIhT
          mQIDAQAB
          -----END PUBLIC KEY-----
# location of the swagger json
springfox:
  documentation:
    swagger:
      v2:
        path: /swagger.json
logging:
  level:
    org.springframework.security: INFO